version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.13.5-stretch
    working_directory: /go/src/github.com/weaveworks/docker-ansible
    steps:
      - checkout
      - setup_remote_docker
      - run: make

      - deploy:
          name: Push image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              docker push weaveworks/docker-ansible:$(./tools/image-tag)
            fi
